### ISSUE TITLE
add PluginFactory

### ISSUE THREAD

**Issue by michielbdejong** [interledgerjs/ilp-plugin-payment-channel-framework#29]
It occurred to me that in the WebSocket server case, we're doing this wrong. :)

Currently, we're telling one plugin to listen on a port. That will work for a sender or a receiver that just has one peer (e.g. my ILSP will connect to my online shop server's WebSocket server to deliver BTP Prepare messages, but I don't expect anyone else to ever connect to that WebSocket URL).

What would be more correct would be to have one Plugin per WebSocket *connection*. So:

```js
const opts = {
 listenOnPort: 443,
 cert: <bla.pdx>
}

const factory = new PluginFactory(opts)

factory.on('clientConnected', async (plugin) => {
  // now we have one plugin, because one peer connected to the WebSocket server
  // which the factory is running.
  await plugin.connect()
  await plugin.sendTransfer(foo)
  await plugin.disconnect()
})
```

**Comment by michielbdejong** [comment]
assigned a bunch of you since so many plugins will be using this, so I guess how we deal with this will now be quite a fundamental issue in the interledgerjs stack.

**Comment by dappelt** [comment]
Agreed, in something like the ILP Kit, the WebSocket server should listen only on one port and hand incoming connections to the correct plugin instance.

On the other hand, if you know there is only one peer connecting to your plugin, it is convenient to tell the plugin directly to listen for incoming connections without having to run a dedicated WebSocket Server.

**Comment by sharafian** [comment]
@justmoon had a discussion about this, and came to the current implementation of payment channel framework (with the websocket server inside of the plugin) because:

- The ILP Kit doesn't have to mix concerns
- Now that we have many ILP nodes other than ILP Kit, it means less reimplementation between them
- It's easier for testing
- Peers are infrequently added/removed so you can proxy the ports to an endpoint with nginx.

I agree that we still need a factory version of the plugin, especially for the case where every user has a trustline. It's impractical to pick a port for every user and then configure it with nginx. I think ideally we should make something that follows the same API as the plugin bells factory (which would allow it to use functions like `listenAll` in the ILP module). It can use the `auth_username` protocol to dynamically decide what balance/transferLog to use for each connection. I think the main issue is deciding how the factory interacts with the database of users, because the exact software and schema used might depend on the implementation.

**Comment by michielbdejong** [comment]
Having nginx proxy different URLs to different local ports and then running 1 WebSocket server per peer, is a very weird way to use websockets, I think. The WebSocket server object has a `'connection'` event, which is called each time a new connection is added. That’s what we should use I think, as describe in the snippet above.

It's important to realize that the `WebSocket` object, when you play the client role, really represents two things at once: the client and, once it has emitted its `'open'` event, the connection that this client has to a server.

When you play the server role, there is one `WebSocket.Server` object which represents the server, that listens on a port. That object emits `'connection'` events, with a `ws` object as argument, and that object represents a *connection*. You can have 0 or 5 or 100 connections open from one server object, even though a WebSocket client object can only have 0 (if it's closed) or 1 (if it's open) connections.

A process should have 1 plugin per peer. If the process plays the client role to a given peer, then this peer's plugin should have a WebSocket client (it can open the websocket from plugin.connect). If this process plays the server role, then the plugin for that peer should have one WebSocket server connection, not an entire WebSocket server! :) There should never be more than one WebSocket server in the process (but there can be multiple WebSocket clients)

**Comment by michielbdejong** [comment]
@sharafian so do you agree now that this is the way to go?

**Comment by sharafian** [comment]
Yeah, I think it's reasonable to say that for applications such as ILP Kit we don't want to run 5 different websocket servers for 5 different peers, because that's a pretty bad configuration experience. I've got a PR open to ILP Kit that adds an endpoint which I think works similarly to how you're describing (although the auth logic needs updating).

However, I don't agree that we should take the websocket server out of plugin payment channel framework. It's not like anybody has to use it, but I find it extremely helpful to use for testing, use in non-Ilp-Kit environments, and development.

If some application doesn't want to use the listener functionality, they can just omit the `listener` parameter, and use `addSocket` directly, as it is exposed by the plugin.

**Comment by michielbdejong** [comment]
ok, will create plugin with empty config, and then call addSocket.
